{% set name = "toolong" %}
{% set version = "1.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/toolong-{{ version }}.tar.gz
  sha256: 49934701f954f9701d37381bed6e0f3dfbea0abe1065fcf1ff35de9eef3bbcf3

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - tl = toolong.cli:run

requirements:
  host:
    - python >=3.8
    - poetry-core
    - pip
  run:
    - python >=3.8
    - click >=8.1.7,<9
    - textual >=0.52.0,<0.53.0
    - typing-extensions >=4.9.0,<5

test:
  imports:
    - toolong
  commands:
    - tl --version
    - pip check
  requires:
    - pip

about:
  home: https://github.com/textualize/toolong
  summary: A terminal log file viewer / tailer / analyzer
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dhirschfeld
