{% set name = "toolong" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/toolong-{{ version }}.tar.gz
  sha256: 03a15563beeddc537541f654a2e957b0bc60a613fcbe4bc8ccc10f6b1b12cef5

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - tl = toolong.cli:run

requirements:
  host:
    - python >=3.8
    - poetry-core
    - pip
  run:
    - python >=3.8
    - click >=8.1.7,<9
    - textual >=0.50.0,<0.51.0
    - typing-extensions >=4.9.0,<5

test:
  imports:
    - toolong
  commands:
    - tl --version
    - pip check
  requires:
    - pip

about:
  home: https://github.com/textualize/toolong
  summary: A terminal log file viewer / tailer / analyzer
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dhirschfeld
