{% set name = "toolong" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/toolong-{{ version }}.tar.gz
  sha256: f8e1db93dbbf356f4f49b44af18d05a32d1b569899fb3cb45eebd48a64257ee9

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - tl = toolong.cli:run

requirements:
  host:
    - python >=3.8
    - poetry-core
    - pip
  run:
    - python >=3.8
    - click >=8.1.7,<9
    - textual >=0.50.0,<1
    - typing-extensions >=4.9.0,<5

test:
  imports:
    - toolong
  commands:
    - tl --version
    - pip check
  requires:
    - pip

about:
  home: https://github.com/textualize/toolong
  summary: A terminal log file viewer / tailer / analyzer
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dhirschfeld
